/******************************************************
 * Interrupt Handlers implementation file.            *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "ac_intr_handler.H"
#include "riscv_intr_handlers.H"

#include "riscv_ih_bhv_macros.H"

//!'using namespace' statement to allow access to all riscv-specific datatypes
using namespace riscv_parms;

// Interrupt handler behavior for interrupt port intp.
void ac_behavior(intp, value, addr) {
}

